### ISSUE TITLE
Add extra kicad files to gitignore

### ISSUE THREAD

**Issue by jhauerst** [Terrapin-Rocket-Team/SRAD_Avionics#18]
There are a bunch of autogenerated kicad files that don't need to be committed, so they should be added to the gitignore for convenience. These include *.kicad_prl files, the fp_info_cache file, and the backups folder and possibly others.

**Comment by DrewBrandt** [comment]
As I understand it, gerber files are not part of the design and do not need to be source-controlled. Is that right? Similarly, I read that files prepended with ~ are autosave files. Is that also right? Here are the changes I've made.

[Blame for .gitignore](https://github.com/Terrapin-Rocket-Team/SRAD_Avionics/blame/18-add-extra-kicad-files-to-gitignore/.gitignore)

I'll make a pull request if you agree with the changes.
