### ISSUE TITLE
Write code for the State class

### ISSUE THREAD

**Issue by varun-un** [Terrapin-Rocket-Team/SRAD_Avionics#30]
Write the main State class, as well as its functions that would run in the `setup()` and `main()` loop, that would encompass the flight computer's state and would handle all of the sensors. All the sensors would be objects within it, and the State class interacts with them and the SD Card to interface between them, as well as query the sensors for data and store it.

**Comment by DrewBrandt** [comment]
Should this be closed since you merged that branch?
