### ISSUE TITLE
Calculations for Low-Pass Filter

### ISSUE THREAD

**Issue by LShapir0** [Terrapin-Rocket-Team/SRAD_Avionics#38]
Calculate values for resistor, capacitor and inductor for a low-pass filter for the MAX-M10s chip.

**Comment by LShapir0** [comment]
![image](https://github.com/Terrapin-Rocket-Team/SRAD_Avionics/assets/147450134/9f7fea2a-157d-4d02-87f2-c3ebd136a382)

L3 - 27 nH, 5%;
Recommended Inductors:
Murata LQG15H, LQW15A series
Johanson Technology L-07W series
Any other inductor with impedance >500 Ω at GNSS
frequency and current rating above 300 mA.
R8 - 10 Ω, 5%, 0.25 W
C14 - 10 nF, 10%, 16 V, X7R

**Comment by LShapir0** [comment]
Since we don't have a 10nH inductor in stock, the best bet is to use the 10nH inductor.

**Comment by varun-un** [comment]
Unified Board v1.1 assembled with `LP_R` as 10Ω, `LP_C` as 10nF, and `FB1` as 68nH
