### ISSUE TITLE
Integrate Kalman Filter

### ISSUE THREAD

**Issue by varun-un** [Terrapin-Rocket-Team/SRAD_Avionics#40]
Integrate the Kalman Filter code into the `State.cpp` file in the `updateState()` function, where it would plug in to update the generic system variables. 

Also, test the KF in C++ by feeding in past launch data to measure accuracy and it works (software-in-the-loop testing).

**Comment by DrewBrandt** [comment]
Kalman filter appears to be working and mostly agrees with unfiltered data. The unfiltered data in this image has a slight error that caused the same data to be reported for 5 time values straight. This appears to have been a bug with the earlier version of the code. It is what causes the sudden jump to the right on the way up at about 350 meters.

![image](https://github.com/Terrapin-Rocket-Team/SRAD_Avionics/assets/158541128/11925a02-bf78-48b8-b3c2-c2ae607647cc)

**Comment by varun-un** [comment]
The jump on the way up may also be due to airbrake, when they open their flaps on the way up, air rushes into the rocket body which changes the pressure which affects the barometer's readings, which in past data from both avionics and airbrake electronics has caused a little jump. As for the same data being reported 5 times, I don't really know but that's probably a bug

**Comment by DrewBrandt** [comment]
My point was more that, had that slight jump not been there, the Kalman filter appears that it would have followed the line exactly, which may not be the intended behavior. That error is not in the data given to the system, only in the data recorded by it for the iteration that I was able to use for comparison.
