### ISSUE TITLE
Modify GPS board to allow for mode selection

### ISSUE THREAD

**Issue by varun-un** [Terrapin-Rocket-Team/SRAD_Avionics#41]
Certain u-blox GPS modules allow for mode selection (page 15 of the [MAX-M10S Integration Manual](https://content.u-blox.com/sites/default/files/MAX-M10S_IntegrationManual_UBX-20053088.pdf)), so try modifying the GPS schematic and breakout to allow us to select the `Airborne >4g` mode.

**Comment by DrewBrandt** [comment]
This is all you need to do if we are using the arduino library and we get it to work:

```python
m10s.setDynamicModel(DYN_MODEL_AIRBORNE4g);
```

**Comment by varun-un** [comment]
Does this work over i2c?

**Comment by DrewBrandt** [comment]
It's from the m10s library, which appears to support both I2C and SPI. I'm pretty sure that if we get the GPS module to work with our current code/the sample code, then it will work with this command.
