### ISSUE TITLE
Live video Raspberry Pi mount design

### ISSUE THREAD

**Issue by jhauerst** [Terrapin-Rocket-Team/SRAD_Avionics#46]
The live video hardware (Raspberry Pi, camera, battery, power board, and radio) will need a mount in the ebay. The mount will be 3D printed, and should be as small and sturdy as possible. Currently, the battery has not been chosen and the power board has not been designed, but the battery will most likely be similar to [this](https://power.tenergy.com/tenergy-nimh-6v-2000mah-side-by-side-receiver-battery-pack-w-hitec-connector-for-rc-aircrafts/). The power board will be mounted on the RPi header pins if possible, but may need to be mounted elsewhere if clearance with the [RPi heatsink](https://www.adafruit.com/product/4341?gad_source=1) is an issue. The radio will likely be mounted on the power board in either situation. The [camera](https://www.amazon.com/Inno-Maker-Camera-Module-OV5647-Raspberry/dp/B07G9VLPZH) will need to be mounted so that it is positioned to look out of a hole in the side of the ebay, so it may get a separate mount. 

Tasks:

- [ ] Design a mount that secures the Raspberry Pi and battery in the ebay
- [ ] Integrate a mount for the power board and camera if necessary
- [ ] 3D print the mount and test fit all components

**Comment by DrewBrandt** [comment]
Closed at some point with development of current eBay design
