### ISSUE TITLE
Add a log file to the SD card.

### ISSUE THREAD

**Issue by DrewBrandt** [Terrapin-Rocket-Team/SRAD_Avionics#61]
Add a logging wrapper that can be used to both write to the SD card and to Serial.

This can be used to aid in debugging processes both during launches and during computer-connected testing.

**Comment by DrewBrandt** [comment]
The implementation I have in mind signifigantly reworks the RecordData and psram libraries to support writing to both sides of the psram. the beginning of it for state data and the end of it for log data. I would also remove the launch dumping of psram to the SD card as the single launch data I have that does that indicates a 2 second break in data. I am making the assumption this is because of the time it took to write to the SD card.

**Comment by varun-un** [comment]
Have the log file write the static data strings from sensors as well
